Algoritmo "Exercício 2"

Var
// Seção de Declarações das variáveis
   nome : caractere
   peso, altura : real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite seu nome:")
   leia(nome)
   
   escreva("Digite sua altura:")
   leia(altura)
   
   escreva("Digite seu peso:")
   leia(peso)
   
   escreval("Seu nome é: " + nome)
   escreval("Seu peso é:", peso, "kg")
   escreval("Sua altura é:", altura, "mts")
Fimalgoritmo